### ISSUE TITLE
Discord link seems to be not working

### ISSUE THREAD

**Issue by tekjar** [stateright/stateright#10]
Title explains it all :)

**Comment by jonnadal** [comment]
Thanks @tekjar for letting me know! I submitted https://github.com/stateright/stateright/commit/d0c94c88430249a3ca3bbbdaf7aa5516582ac655 to (hopefully) fix this.

Would you let me know if the new link works for you?

**Comment by tekjar** [comment]
It doesn't. I tried from my laptop and mobile as well.

**Comment by jonnadal** [comment]
My apologies for the churn @tekjar. Looks like I needed to create an invite: https://discord.gg/JbxGSVP4A6

**Comment by tekjar** [comment]
Works!! Thanks :+1:

**Comment by jonnadal** [comment]
https://github.com/stateright/stateright/commit/265eaee44989f5ceefd5ac21651e1e4612ee1a1d has the final fix. Thanks again @tekjar.
