### ISSUE TITLE
Explorer UI: dynamic property feedback

### ISSUE THREAD

**Issue by jeffa5** [stateright/stateright#22]
When exploring states in the UI it shows the overall properties for all states so far, could it also show the status of the properties at the current state being explored.

My hope is that this will allow us to automatically be told (when clicking through) that we are now in a bad state (violating properties).

**Comment by jonnadal** [comment]
Yes, this is definitely possible. Good idea @jeffa5! Would you like to prepare the PR? Alternatively I'd be happy to take a look into this (although can't commit to a particular turnaround time at the moment).

**Comment by jeffa5** [comment]
I'm not too sure when I'd get to it at the moment either but might be able to have a bit of a poke around here and there.
