### ISSUE TITLE
Order-preserving network flows

### ISSUE THREAD

**Issue by graydon** [stateright/stateright#4]
This is a note about an addition I'm thinking of making -- thought I'd post here before I work on it to ask if it makes sense to you and/or would be welcome.

(Context: the actor system I'm driving with stateright exhibits pretty bad state-space explosion -- 3 peers and 2 consensus cycles finish in "only" a few hundred thousand states, but 3 consensus cycles exceeds 100m states and exhausts memory on my 128gb test box -- so I'm kinda grasping at straws to figure out things to reduce it, and/or whether there's a bug in my code. I'll file a couple other issues as possible avenues I'm considering for discussion of those also.)

The simplest change I can think of is to add another flag concerning the network semantics, such that messages in a given flow don't get reordered: if peer 1 sends messages A then B to peer 2, I'd like to only explore delivery schedules that have A arriving at peer 2 before B. I think this is not an unreasonable variant -- lots of network abstractions preserve order per-flow -- and it'll cut out a lot of the state space, for a reasonably small change.

This would not alter the interleaving of separate flows: if peer 3 sends message C to peer 2, then we'd still explore arrival schedules at peer 2 of each of [C,A,B], [A,C,B], [A,B,C]. Just not [C,B,A], [B,C,A], or [B,A,C].

What do you think?

**Comment by jonnadal** [comment]
This is a great idea! Please do.

Related: I’m working on a commit to add scheduled wake-up events to the checker and JSON/UDP runtime, which allows us to implement these semantics as an actor decorator and presumably model check it for safety/liveness independently of the actors it decorates.

**Comment by jonnadal** [comment]
@graydon https://github.com/stateright/stateright/commit/ccdf49240195f1289b66b8f0b9258cd0db128359 implements a model checked version of the proposed abstraction (ordered reliable link), although it does not implement the associated model checking optimization for actors that will adopt this abstraction.

Please let me know if you'd like me to take a pass at the proposed model checking optimization. ETA would be ~3 weeks, so I also don't want to be a bottleneck if you were planning on picking this up sooner.

BTW you might find https://github.com/stateright/stateright/commit/a700b1f7cbe74a812141c9710daa081af4abfa1d useful for https://github.com/graydon/concorde as it prints out a path to any counterexamples, along with the final state. It doesn't currently print initial/intermediate states as I found that to be a bit too verbose for the scenarios I was model checking, and I tend to use Explorer when I need more detail, but options could be added to print all states if that's valuable. Example output if I introduce a bug into `ordered_reliable_link`:

```
Counterexample for 'ordered' found.

== ACTIONS ==
Deliver { src: Id(0), dst: Id(1), msg: Deliver(2, TestMsg(43)) }
Deliver { src: Id(0), dst: Id(1), msg: Deliver(1, TestMsg(42)) }

== LAST STATE ==
_SystemState {
    actor_states: [
        StateWrapper {
            next_send_seq: 3,
            msgs_pending_ack: {
                1: (
                    Id(
                        1,
                    ),
                    TestMsg(
                        42,
                    ),
                ),
                2: (
                    Id(
                        1,
                    ),
                    TestMsg(
                        43,
                    ),
                ),
            },
            last_delivered_seqs: {},
            wrapped_state: Received(
                [],
            ),
        },
        StateWrapper {
            next_send_seq: 1,
            msgs_pending_ack: {},
            last_delivered_seqs: {
                Id(
                    0,
                ): 1,
            },
            wrapped_state: Received(
                [
                    (
                        Id(
                            0,
                        ),
                        TestMsg(
                            43,
                        ),
                    ),
                    (
                        Id(
                            0,
                        ),
                        TestMsg(
                            42,
                        ),
                    ),
                ],
            ),
        },
    ],
    network: {
        Envelope {
            src: Id(
                0,
            ),
            dst: Id(
                1,
            ),
            msg: Deliver(
                1,
                TestMsg(
                    42,
                ),
            ),
        },
        Envelope {
            src: Id(
                0,
            ),
            dst: Id(
                1,
            ),
            msg: Deliver(
                2,
                TestMsg(
                    43,
                ),
            ),
        },
        Envelope {
            src: Id(
                1,
            ),
            dst: Id(
                0,
            ),
            msg: Ack(
                1,
            ),
        },
        Envelope {
            src: Id(
                1,
            ),
            dst: Id(
                0,
            ),
            msg: Ack(
                2,
            ),
        },
    },
    is_timer_set: [
        true,
        true,
    ],
}
```

**Comment by jonnadal** [comment]
@graydon https://github.com/stateright/stateright/commit/e0648cf6bf885ac3d481d0a15f50b8f9a40562a4 adds this feature, so I am resolving this issue. Thank you for taking the time to share the idea!
