### ISSUE TITLE
Question: Is it possible to share the outputs / states 

### ISSUE THREAD

**Issue by dirvine** [stateright/stateright#46]
First, love the project. Superb work and thanks. 
We are using this a lot now to test some hypothesis and it's proving magnificent. I recently got a larger 96Gb machine to run some larger models. (would love a gpu handoff).

What I would really like to do is share the data with collaborators to let them investigate any counterexamples and associated sequence diagrams. 

Can you suggest any mechanism to do this or perhaps even a route to achieving this.

**Comment by dirvine** [comment]
closing this as it's discussed https://github.com/stateright/stateright/issues/31

Sorry for noise.

**Comment by jonnadal** [comment]
The fact that you can also use that feature is helpful context. Thank you for sharing details about your use case @dirvine!
