### ISSUE TITLE
Heterogenous Actors

### ISSUE THREAD

**Issue by dtwitty** [stateright/stateright#58]
What is the preferred way to model actors of different types, like "client" and "server"?

The [2pc example](https://github.com/stateright/stateright/blob/master/examples/2pc.rs) seems to model this with a shared state, but I'd like to use Actors because they are easier to reason about. However, ActorModel appears to only accept a single Actor type.

I see there is a [Choice Actor](https://docs.rs/stateright/latest/stateright/actor/trait.Actor.html#impl-Actor-for-Choice%3CA1,+A2%3E), that simply requires the same type for messages and timers. Should we use that? What if we'd like more than two actor types, like "client, server, database" or similar?

**Comment by degregat** [comment]
@dtwitty It seems `Choice` is an [Inductive Type](https://docs.rs/choice/0.0.2/choice/#composition-pattern) and can be used to implement your use case. 

You can find an example with three types in the [tests](https://github.com/stateright/stateright/blob/54f037c290e216847eee8a204ef55a731d4959ef/src/actor/model.rs#L1221C20-L1221C20).

I'm working on a similar application of it right now and can paste a link here once it's done for another example.

**Comment by jonnadal** [comment]
Thank you @degregat for sharing that pointer! @dtwitty does that help?

**Comment by jonnadal** [comment]
Closing this issue as @degregat added a reference example when resolving https://github.com/stateright/stateright/pull/62 with 88f1676733ff9e7882fac249b3ff462cb0a3c499.
