### ISSUE TITLE
Tag your releases

### ISSUE THREAD

**Issue by hardliner66** [stateright/stateright#59]
Please consider tagging your releases, so that there is a snapshot to go to, when working with specific versions.

Right now I'm trying to get the examples to run standalone, but without a proper tag it's hard to get the correct source version of the example matching to the version in my lock-file. Right now it might be easily fixable, but it's only gonna get harder moving forward.

**Comment by jonnadal** [comment]
Hi @hardliner66. Thanks for your interest in the project and for taking the time to share this feedback. I'll begin tagging versions with the next release.

In the meantime you should be able to find the commit associated with each particular release based on the description. e.g.
```sh
$ git log --oneline --grep '^version' |head
c43562e version 0.28.0
437ca7c version 0.27.1
52ad7fe version 0.27.0
20b8dbc version 0.26.1
48ebda5 version 0.26.0
41e84a9 version 0.25.0
83ded53 version 0.24.1
849605f version 0.24.0
5319b40 version 0.23.3
8e93f67 version 0.23.2
```

**Comment by jonnadal** [comment]
Began tagging releases w/ v0.30.1: https://github.com/stateright/stateright/tags

Thanks again for this suggestion @hardliner66!
